name: Cache test

on:
  workflow_dispatch:

jobs:
  cache:
    name: Test cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      id: cache
      uses: actions/cache@v3
      env:
        cache-name: cache-maven
      with:
        path: |
          ${{ github.workspace }}/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    - name: Cache hit
      if: steps.cache.outputs.cache-hit != 'true'
      run: echo "Cache missed"
    
    - name: Populate m2 to mock Maven build
      run: |
        mkdir -pv ${{ github.workspace }}/.m2/repository/
        echo "hellooooooooooooooooooooooooooooooooooo" > ${{ github.workspace }}/.m2/repository/hello.txt
