name: Container image pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  changes:
    name: Check which container image was updated
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            alpine: 
              - 'alpine/**'
            ubuntu: 
              - 'ubuntu/**'

  build:
    name: Build and push image
    needs: changes
    strategy:
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}
    uses: nascit/docker-build/.github/workflows/docker-publish.yml@main
    with:
      image: ${{ matrix.image }}